def mode_set(mode: str = "OBJECT", toggle: bool = False) -> None: ...
def select_all(action: str = "TOGGLE") -> None: ...
def delete(use_global: bool = False, confirm: bool = True) -> None: ...
def modifier_apply(modifier: str = "", report: bool = False) -> None: ...
