def mode_set(mode: str = "OBJECT", toggle: bool = False) -> None: ...
def select_all(action: str = "TOGGLE") -> None: ...
def delete(use_global: bool = False, confirm: bool = True) -> None: ...
def modifier_apply(modifier: str = "", report: bool = False) -> None: ...
def load_reference_image(
    filepath: str = "",
    filter_image: bool = True,
    filter_folder: bool = True,
    view_align: bool = True,
) -> None: ...
