import bpy
import typing as _typing


class BMesh:
    faces: BMFaceSeq = ...
    edges: BMEdgeSeq = ...
    verts: BMVertSeq = ...

    def from_mesh(
        self,
        mesh: bpy.types.Mesh,
        face_normals: _typing.Any = True,  # pyre-fixme[2]: shouldn't use Any
        vertex_normals: _typing.Any = True,  # pyre-fixme[2]: shouldn't use Any
        use_shape_key: bool = False,
        shape_key_index: int = 0,
    ) -> None: ...
    def to_mesh(self, mesh: bpy.types.Mesh) -> None: ...
    def free(self) -> None: ...


class BMFace: ...


class BMEdge: ...


class BMVert: ...


class BMEdgeSeq(_typing.List[BMEdge]): ...


class BMFaceSeq(_typing.List[BMFace]): ...


class BMVertSeq(_typing.List[BMVert]): ...
